/*
 * generated by Xtext
 */
package knowledge.xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class KnowDEECoUiModule extends knowledge.xtext.ui.AbstractKnowDEECoUiModule {
	public KnowDEECoUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
