/*
* generated by Xtext
*/
package knowledge.xtext.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import knowledge.xtext.services.KnowDEECoGrammarAccess;

public class KnowDEECoParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private KnowDEECoGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected knowledge.xtext.parser.antlr.internal.InternalKnowDEECoParser createParser(XtextTokenStream stream) {
		return new knowledge.xtext.parser.antlr.internal.InternalKnowDEECoParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "DEECoModel";
	}
	
	public KnowDEECoGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(KnowDEECoGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
