/*
* generated by Xtext
*/
package knowledge.xtext.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class KnowDEECoAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("knowledge/xtext/parser/antlr/internal/InternalKnowDEECo.tokens");
	}
}
