/*
 * generated by Xtext
 */
package knowledge.xtext;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class KnowDEECoRuntimeModule extends knowledge.xtext.AbstractKnowDEECoRuntimeModule {

}
