/*
* generated by Xtext
*/
package knowledge.xtext.ui.contentassist;

import knowledge.xtext.ui.contentassist.AbstractKnowDEECoProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class KnowDEECoProposalProvider extends AbstractKnowDEECoProposalProvider {

}
