/*
* generated by Xtext
*/
package knowledge.xtext.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class KnowDEECoOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
