/*
 * generated by Xtext
 */
package knowledge.xtext.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import knowledge.xtext.ui.internal.KnowDEECoActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class KnowDEECoExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return KnowDEECoActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return KnowDEECoActivator.getInstance().getInjector(KnowDEECoActivator.KNOWLEDGE_XTEXT_KNOWDEECO);
	}
	
}
