/*
* generated by Xtext
*/

package knowledge.xtext.services;

import com.google.inject.Singleton;
import com.google.inject.Inject;

import java.util.List;

import org.eclipse.xtext.*;
import org.eclipse.xtext.service.GrammarProvider;
import org.eclipse.xtext.service.AbstractElementFinder.*;

import org.eclipse.xtext.common.services.TerminalsGrammarAccess;

@Singleton
public class KnowDEECoGrammarAccess extends AbstractGrammarElementFinder {
	
	
	public class DEECoModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "DEECoModel");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cDEECoModelAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cDEECoModelKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cElementsKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3_1 = (Keyword)cGroup_3.eContents().get(1);
		private final Assignment cElementsAssignment_3_2 = (Assignment)cGroup_3.eContents().get(2);
		private final RuleCall cElementsAbstractElementParserRuleCall_3_2_0 = (RuleCall)cElementsAssignment_3_2.eContents().get(0);
		private final Group cGroup_3_3 = (Group)cGroup_3.eContents().get(3);
		private final Keyword cCommaKeyword_3_3_0 = (Keyword)cGroup_3_3.eContents().get(0);
		private final Assignment cElementsAssignment_3_3_1 = (Assignment)cGroup_3_3.eContents().get(1);
		private final RuleCall cElementsAbstractElementParserRuleCall_3_3_1_0 = (RuleCall)cElementsAssignment_3_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_3_4 = (Keyword)cGroup_3.eContents().get(4);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cKnowledgesKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cKnowledgesAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final RuleCall cKnowledgesAbstractKnowledgeParserRuleCall_4_2_0 = (RuleCall)cKnowledgesAssignment_4_2.eContents().get(0);
		private final Group cGroup_4_3 = (Group)cGroup_4.eContents().get(3);
		private final Keyword cCommaKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final Assignment cKnowledgesAssignment_4_3_1 = (Assignment)cGroup_4_3.eContents().get(1);
		private final RuleCall cKnowledgesAbstractKnowledgeParserRuleCall_4_3_1_0 = (RuleCall)cKnowledgesAssignment_4_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//DEECoModel:
		//
		//	{DEECoModel} "DEECoModel" "{" ("elements" "{" elements+=AbstractElement ("," elements+=AbstractElement)* "}")?
		//
		//	("knowledges" "{" knowledges+=AbstractKnowledge ("," knowledges+=AbstractKnowledge)* "}")? "}";
		public ParserRule getRule() { return rule; }

		//{DEECoModel} "DEECoModel" "{" ("elements" "{" elements+=AbstractElement ("," elements+=AbstractElement)* "}")?
		//
		//("knowledges" "{" knowledges+=AbstractKnowledge ("," knowledges+=AbstractKnowledge)* "}")? "}"
		public Group getGroup() { return cGroup; }

		//{DEECoModel}
		public Action getDEECoModelAction_0() { return cDEECoModelAction_0; }

		//"DEECoModel"
		public Keyword getDEECoModelKeyword_1() { return cDEECoModelKeyword_1; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//("elements" "{" elements+=AbstractElement ("," elements+=AbstractElement)* "}")?
		public Group getGroup_3() { return cGroup_3; }

		//"elements"
		public Keyword getElementsKeyword_3_0() { return cElementsKeyword_3_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_3_1() { return cLeftCurlyBracketKeyword_3_1; }

		//elements+=AbstractElement
		public Assignment getElementsAssignment_3_2() { return cElementsAssignment_3_2; }

		//AbstractElement
		public RuleCall getElementsAbstractElementParserRuleCall_3_2_0() { return cElementsAbstractElementParserRuleCall_3_2_0; }

		//("," elements+=AbstractElement)*
		public Group getGroup_3_3() { return cGroup_3_3; }

		//","
		public Keyword getCommaKeyword_3_3_0() { return cCommaKeyword_3_3_0; }

		//elements+=AbstractElement
		public Assignment getElementsAssignment_3_3_1() { return cElementsAssignment_3_3_1; }

		//AbstractElement
		public RuleCall getElementsAbstractElementParserRuleCall_3_3_1_0() { return cElementsAbstractElementParserRuleCall_3_3_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_3_4() { return cRightCurlyBracketKeyword_3_4; }

		//("knowledges" "{" knowledges+=AbstractKnowledge ("," knowledges+=AbstractKnowledge)* "}")?
		public Group getGroup_4() { return cGroup_4; }

		//"knowledges"
		public Keyword getKnowledgesKeyword_4_0() { return cKnowledgesKeyword_4_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_4_1() { return cLeftCurlyBracketKeyword_4_1; }

		//knowledges+=AbstractKnowledge
		public Assignment getKnowledgesAssignment_4_2() { return cKnowledgesAssignment_4_2; }

		//AbstractKnowledge
		public RuleCall getKnowledgesAbstractKnowledgeParserRuleCall_4_2_0() { return cKnowledgesAbstractKnowledgeParserRuleCall_4_2_0; }

		//("," knowledges+=AbstractKnowledge)*
		public Group getGroup_4_3() { return cGroup_4_3; }

		//","
		public Keyword getCommaKeyword_4_3_0() { return cCommaKeyword_4_3_0; }

		//knowledges+=AbstractKnowledge
		public Assignment getKnowledgesAssignment_4_3_1() { return cKnowledgesAssignment_4_3_1; }

		//AbstractKnowledge
		public RuleCall getKnowledgesAbstractKnowledgeParserRuleCall_4_3_1_0() { return cKnowledgesAbstractKnowledgeParserRuleCall_4_3_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_4_4() { return cRightCurlyBracketKeyword_4_4; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}

	public class AbstractElementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "AbstractElement");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cEnsembleParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cProcessParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//AbstractElement:
		//
		//	Ensemble | Process;
		public ParserRule getRule() { return rule; }

		//Ensemble | Process
		public Alternatives getAlternatives() { return cAlternatives; }

		//Ensemble
		public RuleCall getEnsembleParserRuleCall_0() { return cEnsembleParserRuleCall_0; }

		//Process
		public RuleCall getProcessParserRuleCall_1() { return cProcessParserRuleCall_1; }
	}

	public class AbstractKnowledgeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "AbstractKnowledge");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cKnowledgeElementParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cLeafParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//AbstractKnowledge:
		//
		//	KnowledgeElement | Leaf;
		public ParserRule getRule() { return rule; }

		//KnowledgeElement | Leaf
		public Alternatives getAlternatives() { return cAlternatives; }

		//KnowledgeElement
		public RuleCall getKnowledgeElementParserRuleCall_0() { return cKnowledgeElementParserRuleCall_0; }

		//Leaf
		public RuleCall getLeafParserRuleCall_1() { return cLeafParserRuleCall_1; }
	}

	public class KnowledgeNodeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "KnowledgeNode");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cKnowledgeElementParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cLeafParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//KnowledgeNode:
		//
		//	KnowledgeElement | Leaf;
		public ParserRule getRule() { return rule; }

		//KnowledgeElement | Leaf
		public Alternatives getAlternatives() { return cAlternatives; }

		//KnowledgeElement
		public RuleCall getKnowledgeElementParserRuleCall_0() { return cKnowledgeElementParserRuleCall_0; }

		//Leaf
		public RuleCall getLeafParserRuleCall_1() { return cLeafParserRuleCall_1; }
	}

	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString returns ecore::EString:
		//
		//	STRING | ID;
		public ParserRule getRule() { return rule; }

		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }

		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }

		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}

	public class EIntElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "EInt");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		
		//EInt returns ecore::EInt:
		//
		//	"-"? INT;
		public ParserRule getRule() { return rule; }

		//"-"? INT
		public Group getGroup() { return cGroup; }

		//"-"?
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }

		//INT
		public RuleCall getINTTerminalRuleCall_1() { return cINTTerminalRuleCall_1; }
	}

	public class EnsembleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Ensemble");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cEnsembleAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cEnsembleKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cPeriodKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cPeriodAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cPeriodEIntParserRuleCall_4_1_0 = (RuleCall)cPeriodAssignment_4_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Ensemble:
		//
		//	{Ensemble} "Ensemble" name=EString "{" ("period" period=EInt)? "}";
		public ParserRule getRule() { return rule; }

		//{Ensemble} "Ensemble" name=EString "{" ("period" period=EInt)? "}"
		public Group getGroup() { return cGroup; }

		//{Ensemble}
		public Action getEnsembleAction_0() { return cEnsembleAction_0; }

		//"Ensemble"
		public Keyword getEnsembleKeyword_1() { return cEnsembleKeyword_1; }

		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }

		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }

		//("period" period=EInt)?
		public Group getGroup_4() { return cGroup_4; }

		//"period"
		public Keyword getPeriodKeyword_4_0() { return cPeriodKeyword_4_0; }

		//period=EInt
		public Assignment getPeriodAssignment_4_1() { return cPeriodAssignment_4_1; }

		//EInt
		public RuleCall getPeriodEIntParserRuleCall_4_1_0() { return cPeriodEIntParserRuleCall_4_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}

	public class ProcessElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Process");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cProcessAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cProcessKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cPeriodKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cPeriodAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cPeriodEIntParserRuleCall_4_1_0 = (RuleCall)cPeriodAssignment_4_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Process:
		//
		//	{Process} "Process" name=EString "{" ("period" period=EInt)? "}";
		public ParserRule getRule() { return rule; }

		//{Process} "Process" name=EString "{" ("period" period=EInt)? "}"
		public Group getGroup() { return cGroup; }

		//{Process}
		public Action getProcessAction_0() { return cProcessAction_0; }

		//"Process"
		public Keyword getProcessKeyword_1() { return cProcessKeyword_1; }

		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }

		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }

		//("period" period=EInt)?
		public Group getGroup_4() { return cGroup_4; }

		//"period"
		public Keyword getPeriodKeyword_4_0() { return cPeriodKeyword_4_0; }

		//period=EInt
		public Assignment getPeriodAssignment_4_1() { return cPeriodAssignment_4_1; }

		//EInt
		public RuleCall getPeriodEIntParserRuleCall_4_1_0() { return cPeriodEIntParserRuleCall_4_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}

	public class KnowledgeElementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "KnowledgeElement");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cKnowledgeElementKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cReaderKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_3_1 = (Keyword)cGroup_3.eContents().get(1);
		private final Assignment cReaderAssignment_3_2 = (Assignment)cGroup_3.eContents().get(2);
		private final CrossReference cReaderAbstractElementCrossReference_3_2_0 = (CrossReference)cReaderAssignment_3_2.eContents().get(0);
		private final RuleCall cReaderAbstractElementEStringParserRuleCall_3_2_0_1 = (RuleCall)cReaderAbstractElementCrossReference_3_2_0.eContents().get(1);
		private final Group cGroup_3_3 = (Group)cGroup_3.eContents().get(3);
		private final Keyword cCommaKeyword_3_3_0 = (Keyword)cGroup_3_3.eContents().get(0);
		private final Assignment cReaderAssignment_3_3_1 = (Assignment)cGroup_3_3.eContents().get(1);
		private final CrossReference cReaderAbstractElementCrossReference_3_3_1_0 = (CrossReference)cReaderAssignment_3_3_1.eContents().get(0);
		private final RuleCall cReaderAbstractElementEStringParserRuleCall_3_3_1_0_1 = (RuleCall)cReaderAbstractElementCrossReference_3_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_3_4 = (Keyword)cGroup_3.eContents().get(4);
		private final Keyword cChildKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Keyword cLeftCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cChildAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cChildKnowledgeNodeParserRuleCall_6_0 = (RuleCall)cChildAssignment_6.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cCommaKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cChildAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cChildKnowledgeNodeParserRuleCall_7_1_0 = (RuleCall)cChildAssignment_7_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Keyword cRightCurlyBracketKeyword_9 = (Keyword)cGroup.eContents().get(9);
		
		//KnowledgeElement:
		//
		//	"KnowledgeElement" name=EString "{" ("reader" "(" reader+=[AbstractElement|EString] (","
		//
		//	reader+=[AbstractElement|EString])* ")")? "child" "{" child+=KnowledgeNode ("," child+=KnowledgeNode)* "}" "}";
		public ParserRule getRule() { return rule; }

		//"KnowledgeElement" name=EString "{" ("reader" "(" reader+=[AbstractElement|EString] (","
		//
		//reader+=[AbstractElement|EString])* ")")? "child" "{" child+=KnowledgeNode ("," child+=KnowledgeNode)* "}" "}"
		public Group getGroup() { return cGroup; }

		//"KnowledgeElement"
		public Keyword getKnowledgeElementKeyword_0() { return cKnowledgeElementKeyword_0; }

		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//("reader" "(" reader+=[AbstractElement|EString] ("," reader+=[AbstractElement|EString])* ")")?
		public Group getGroup_3() { return cGroup_3; }

		//"reader"
		public Keyword getReaderKeyword_3_0() { return cReaderKeyword_3_0; }

		//"("
		public Keyword getLeftParenthesisKeyword_3_1() { return cLeftParenthesisKeyword_3_1; }

		//reader+=[AbstractElement|EString]
		public Assignment getReaderAssignment_3_2() { return cReaderAssignment_3_2; }

		//[AbstractElement|EString]
		public CrossReference getReaderAbstractElementCrossReference_3_2_0() { return cReaderAbstractElementCrossReference_3_2_0; }

		//EString
		public RuleCall getReaderAbstractElementEStringParserRuleCall_3_2_0_1() { return cReaderAbstractElementEStringParserRuleCall_3_2_0_1; }

		//("," reader+=[AbstractElement|EString])*
		public Group getGroup_3_3() { return cGroup_3_3; }

		//","
		public Keyword getCommaKeyword_3_3_0() { return cCommaKeyword_3_3_0; }

		//reader+=[AbstractElement|EString]
		public Assignment getReaderAssignment_3_3_1() { return cReaderAssignment_3_3_1; }

		//[AbstractElement|EString]
		public CrossReference getReaderAbstractElementCrossReference_3_3_1_0() { return cReaderAbstractElementCrossReference_3_3_1_0; }

		//EString
		public RuleCall getReaderAbstractElementEStringParserRuleCall_3_3_1_0_1() { return cReaderAbstractElementEStringParserRuleCall_3_3_1_0_1; }

		//")"
		public Keyword getRightParenthesisKeyword_3_4() { return cRightParenthesisKeyword_3_4; }

		//"child"
		public Keyword getChildKeyword_4() { return cChildKeyword_4; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_5() { return cLeftCurlyBracketKeyword_5; }

		//child+=KnowledgeNode
		public Assignment getChildAssignment_6() { return cChildAssignment_6; }

		//KnowledgeNode
		public RuleCall getChildKnowledgeNodeParserRuleCall_6_0() { return cChildKnowledgeNodeParserRuleCall_6_0; }

		//("," child+=KnowledgeNode)*
		public Group getGroup_7() { return cGroup_7; }

		//","
		public Keyword getCommaKeyword_7_0() { return cCommaKeyword_7_0; }

		//child+=KnowledgeNode
		public Assignment getChildAssignment_7_1() { return cChildAssignment_7_1; }

		//KnowledgeNode
		public RuleCall getChildKnowledgeNodeParserRuleCall_7_1_0() { return cChildKnowledgeNodeParserRuleCall_7_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_9() { return cRightCurlyBracketKeyword_9; }
	}

	public class LeafElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Leaf");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cLeafAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cLeafKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cTypeKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cTypeAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cTypeEStringParserRuleCall_4_1_0 = (RuleCall)cTypeAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cReaderKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Assignment cReaderAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final CrossReference cReaderAbstractElementCrossReference_5_2_0 = (CrossReference)cReaderAssignment_5_2.eContents().get(0);
		private final RuleCall cReaderAbstractElementEStringParserRuleCall_5_2_0_1 = (RuleCall)cReaderAbstractElementCrossReference_5_2_0.eContents().get(1);
		private final Group cGroup_5_3 = (Group)cGroup_5.eContents().get(3);
		private final Keyword cCommaKeyword_5_3_0 = (Keyword)cGroup_5_3.eContents().get(0);
		private final Assignment cReaderAssignment_5_3_1 = (Assignment)cGroup_5_3.eContents().get(1);
		private final CrossReference cReaderAbstractElementCrossReference_5_3_1_0 = (CrossReference)cReaderAssignment_5_3_1.eContents().get(0);
		private final RuleCall cReaderAbstractElementEStringParserRuleCall_5_3_1_0_1 = (RuleCall)cReaderAbstractElementCrossReference_5_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_5_4 = (Keyword)cGroup_5.eContents().get(4);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cWriterKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cWriterAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final CrossReference cWriterAbstractElementCrossReference_6_1_0 = (CrossReference)cWriterAssignment_6_1.eContents().get(0);
		private final RuleCall cWriterAbstractElementEStringParserRuleCall_6_1_0_1 = (RuleCall)cWriterAbstractElementCrossReference_6_1_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//Leaf:
		//
		//	{Leaf} "Leaf" name=EString "{" ("type" type=EString)? ("reader" "(" reader+=[AbstractElement|EString] (","
		//
		//	reader+=[AbstractElement|EString])* ")")? ("writer" writer=[AbstractElement|EString])? "}";
		public ParserRule getRule() { return rule; }

		//{Leaf} "Leaf" name=EString "{" ("type" type=EString)? ("reader" "(" reader+=[AbstractElement|EString] (","
		//
		//reader+=[AbstractElement|EString])* ")")? ("writer" writer=[AbstractElement|EString])? "}"
		public Group getGroup() { return cGroup; }

		//{Leaf}
		public Action getLeafAction_0() { return cLeafAction_0; }

		//"Leaf"
		public Keyword getLeafKeyword_1() { return cLeafKeyword_1; }

		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }

		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }

		//("type" type=EString)?
		public Group getGroup_4() { return cGroup_4; }

		//"type"
		public Keyword getTypeKeyword_4_0() { return cTypeKeyword_4_0; }

		//type=EString
		public Assignment getTypeAssignment_4_1() { return cTypeAssignment_4_1; }

		//EString
		public RuleCall getTypeEStringParserRuleCall_4_1_0() { return cTypeEStringParserRuleCall_4_1_0; }

		//("reader" "(" reader+=[AbstractElement|EString] ("," reader+=[AbstractElement|EString])* ")")?
		public Group getGroup_5() { return cGroup_5; }

		//"reader"
		public Keyword getReaderKeyword_5_0() { return cReaderKeyword_5_0; }

		//"("
		public Keyword getLeftParenthesisKeyword_5_1() { return cLeftParenthesisKeyword_5_1; }

		//reader+=[AbstractElement|EString]
		public Assignment getReaderAssignment_5_2() { return cReaderAssignment_5_2; }

		//[AbstractElement|EString]
		public CrossReference getReaderAbstractElementCrossReference_5_2_0() { return cReaderAbstractElementCrossReference_5_2_0; }

		//EString
		public RuleCall getReaderAbstractElementEStringParserRuleCall_5_2_0_1() { return cReaderAbstractElementEStringParserRuleCall_5_2_0_1; }

		//("," reader+=[AbstractElement|EString])*
		public Group getGroup_5_3() { return cGroup_5_3; }

		//","
		public Keyword getCommaKeyword_5_3_0() { return cCommaKeyword_5_3_0; }

		//reader+=[AbstractElement|EString]
		public Assignment getReaderAssignment_5_3_1() { return cReaderAssignment_5_3_1; }

		//[AbstractElement|EString]
		public CrossReference getReaderAbstractElementCrossReference_5_3_1_0() { return cReaderAbstractElementCrossReference_5_3_1_0; }

		//EString
		public RuleCall getReaderAbstractElementEStringParserRuleCall_5_3_1_0_1() { return cReaderAbstractElementEStringParserRuleCall_5_3_1_0_1; }

		//")"
		public Keyword getRightParenthesisKeyword_5_4() { return cRightParenthesisKeyword_5_4; }

		//("writer" writer=[AbstractElement|EString])?
		public Group getGroup_6() { return cGroup_6; }

		//"writer"
		public Keyword getWriterKeyword_6_0() { return cWriterKeyword_6_0; }

		//writer=[AbstractElement|EString]
		public Assignment getWriterAssignment_6_1() { return cWriterAssignment_6_1; }

		//[AbstractElement|EString]
		public CrossReference getWriterAbstractElementCrossReference_6_1_0() { return cWriterAbstractElementCrossReference_6_1_0; }

		//EString
		public RuleCall getWriterAbstractElementEStringParserRuleCall_6_1_0_1() { return cWriterAbstractElementEStringParserRuleCall_6_1_0_1; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}
	
	
	private DEECoModelElements pDEECoModel;
	private AbstractElementElements pAbstractElement;
	private AbstractKnowledgeElements pAbstractKnowledge;
	private KnowledgeNodeElements pKnowledgeNode;
	private EStringElements pEString;
	private EIntElements pEInt;
	private EnsembleElements pEnsemble;
	private ProcessElements pProcess;
	private KnowledgeElementElements pKnowledgeElement;
	private LeafElements pLeaf;
	
	private final Grammar grammar;

	private TerminalsGrammarAccess gaTerminals;

	@Inject
	public KnowDEECoGrammarAccess(GrammarProvider grammarProvider,
		TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("knowledge.xtext.KnowDEECo".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	
	public Grammar getGrammar() {
		return grammar;
	}
	

	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//DEECoModel:
	//
	//	{DEECoModel} "DEECoModel" "{" ("elements" "{" elements+=AbstractElement ("," elements+=AbstractElement)* "}")?
	//
	//	("knowledges" "{" knowledges+=AbstractKnowledge ("," knowledges+=AbstractKnowledge)* "}")? "}";
	public DEECoModelElements getDEECoModelAccess() {
		return (pDEECoModel != null) ? pDEECoModel : (pDEECoModel = new DEECoModelElements());
	}
	
	public ParserRule getDEECoModelRule() {
		return getDEECoModelAccess().getRule();
	}

	//AbstractElement:
	//
	//	Ensemble | Process;
	public AbstractElementElements getAbstractElementAccess() {
		return (pAbstractElement != null) ? pAbstractElement : (pAbstractElement = new AbstractElementElements());
	}
	
	public ParserRule getAbstractElementRule() {
		return getAbstractElementAccess().getRule();
	}

	//AbstractKnowledge:
	//
	//	KnowledgeElement | Leaf;
	public AbstractKnowledgeElements getAbstractKnowledgeAccess() {
		return (pAbstractKnowledge != null) ? pAbstractKnowledge : (pAbstractKnowledge = new AbstractKnowledgeElements());
	}
	
	public ParserRule getAbstractKnowledgeRule() {
		return getAbstractKnowledgeAccess().getRule();
	}

	//KnowledgeNode:
	//
	//	KnowledgeElement | Leaf;
	public KnowledgeNodeElements getKnowledgeNodeAccess() {
		return (pKnowledgeNode != null) ? pKnowledgeNode : (pKnowledgeNode = new KnowledgeNodeElements());
	}
	
	public ParserRule getKnowledgeNodeRule() {
		return getKnowledgeNodeAccess().getRule();
	}

	//EString returns ecore::EString:
	//
	//	STRING | ID;
	public EStringElements getEStringAccess() {
		return (pEString != null) ? pEString : (pEString = new EStringElements());
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}

	//EInt returns ecore::EInt:
	//
	//	"-"? INT;
	public EIntElements getEIntAccess() {
		return (pEInt != null) ? pEInt : (pEInt = new EIntElements());
	}
	
	public ParserRule getEIntRule() {
		return getEIntAccess().getRule();
	}

	//Ensemble:
	//
	//	{Ensemble} "Ensemble" name=EString "{" ("period" period=EInt)? "}";
	public EnsembleElements getEnsembleAccess() {
		return (pEnsemble != null) ? pEnsemble : (pEnsemble = new EnsembleElements());
	}
	
	public ParserRule getEnsembleRule() {
		return getEnsembleAccess().getRule();
	}

	//Process:
	//
	//	{Process} "Process" name=EString "{" ("period" period=EInt)? "}";
	public ProcessElements getProcessAccess() {
		return (pProcess != null) ? pProcess : (pProcess = new ProcessElements());
	}
	
	public ParserRule getProcessRule() {
		return getProcessAccess().getRule();
	}

	//KnowledgeElement:
	//
	//	"KnowledgeElement" name=EString "{" ("reader" "(" reader+=[AbstractElement|EString] (","
	//
	//	reader+=[AbstractElement|EString])* ")")? "child" "{" child+=KnowledgeNode ("," child+=KnowledgeNode)* "}" "}";
	public KnowledgeElementElements getKnowledgeElementAccess() {
		return (pKnowledgeElement != null) ? pKnowledgeElement : (pKnowledgeElement = new KnowledgeElementElements());
	}
	
	public ParserRule getKnowledgeElementRule() {
		return getKnowledgeElementAccess().getRule();
	}

	//Leaf:
	//
	//	{Leaf} "Leaf" name=EString "{" ("type" type=EString)? ("reader" "(" reader+=[AbstractElement|EString] (","
	//
	//	reader+=[AbstractElement|EString])* ")")? ("writer" writer=[AbstractElement|EString])? "}";
	public LeafElements getLeafAccess() {
		return (pLeaf != null) ? pLeaf : (pLeaf = new LeafElements());
	}
	
	public ParserRule getLeafRule() {
		return getLeafAccess().getRule();
	}

	//terminal ID:
	//
	//	"^"? ("a".."z" | "A".."Z" | "_") ("a".."z" | "A".."Z" | "_" | "0".."9")*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	} 

	//terminal INT returns ecore::EInt:
	//
	//	"0".."9"+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	} 

	//terminal STRING:
	//
	//	"\"" ("\\" ("b" | "t" | "n" | "f" | "r" | "u" | "\"" | "\'" | "\\") | !("\\" | "\""))* "\"" | "\'" ("\\" ("b" | "t" |
	//
	//	"n" | "f" | "r" | "u" | "\"" | "\'" | "\\") | !("\\" | "\'"))* "\'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	} 

	//terminal ML_COMMENT:
	//
	//	"/ *"->"* /";
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	} 

	//terminal SL_COMMENT:
	//
	//	"//" !("\n" | "\r")* ("\r"? "\n")?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	} 

	//terminal WS:
	//
	//	(" " | "\t" | "\r" | "\n")+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	} 

	//terminal ANY_OTHER:
	//
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	} 
}
